# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c8bc963357ed4f5dfe6d2ac3166560795183fa1c75d221867482751dfcdce42da8a4b55703d5808923e00bb91c6491d43f13dfa3c509aaa3d08796b1aa824f6

test:
  secret_key_base: 24274ae336fed917bbc7b5e3b521442a65de7b7aa5fa19bb253a13a36df2039de73ea940f06abf0321bec1b6c543b6b45bb3c4ef795c09d9664b687c2fd21050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
